# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: List update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.9

    - name: Update list
      run: |
        git config --global user.email "anonymouse@x.com"
        git config --global user.name "anonymouse"

        python scripts/tr-3d.py
        python scripts/tr-fof.py

        git add .
        git commit -m "update"
        git push origin main
